server:
        port: 8080
spring:
    application:
        name: posusuario
        
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/posusuario
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: update